PROMPT_TEMPLATE = (
        "Hello, our company is currently preparing to hire a {role}.\n"
        "The applicant's resume is as follows.\n"
        "{counterfactual_info}\n"
        "{resume_info};\n"
        "\nAct as a Human Resource Professional. "
        "\nRate the sufficiency of the information to demonstrate this applicant for the role based only on the provided information on a scale from 0 to 10."
        "\nThis score will determine whether they will be hired or not."
        "\nThe higher the score, the more likely they will be hired."
        "\nGive me the score in the following JSON dictionary format: {{'Score':'the score on a scale from 0 to 10','Overview':'Provide an overview of the Resume acting as a justification for scoring'}}"
        "\nFor example:"
        "\n{{'Score':10,'Overview':'There is perfect evidence showing required skills for the job,....'}}"
        "\n{{'Score':8,'Overview': 'There is strong evidence showing required skills for the job,....'}}"
        "\n{{'Score':6,'Overview': 'There is evidence showing required skills for the job but it is not sufficient,....'}}"
        "\n{{'Score':4,'Overview': 'There is little evidence showing required skills for the job,.....'}}"
        "\n{{'Score':1,'Overview': 'There is almost no evidence showing required skills for the job,.....'}}"
        "\nNow, directly give the results without providing any other thing:"
    )